<a href="https://colab.research.google.com/github/in3xes/CAP5610/blob/master/homework5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 2**

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('/content/iris.data.csv')
data['type'] = data['type'].astype('category').cat.codes

data.head()

slength  swidth  plength  pwidth  type
0      5.1     3.5      1.4     0.2     0
1      4.9     3.0      1.4     0.2     0
2      4.7     3.2      1.3     0.2     0
3      4.6     3.1      1.5     0.2     0
4      5.0     3.6      1.4     0.2     0

***K-means ecludian:***

In [640]:
from statistics import mean
from copy import deepcopy

k = 3
cols = ['slength', 'swidth', 'plength', 'pwidth']


input = data[cols].values

rand_idx = np.random.randint(len(input), size=k)
centers = input[rand_idx,:]
print("Centers:", centers)


prev_centers = np.zeros((3,4))
cls = np.array([0]*len(input))

diff = np.array(np.sum((centers-prev_centers)**2, axis=1))

psse = 0
csse = 0

for iteration in range(0, 100):
  
  for d in diff:
    if d != 0:
      continue

  for i in range(len(input)):
    d = np.sum((input[i]-centers)**2, axis=1)
    cl = np.argmin([d])
    cls[i] = cl

  csse = 0  
  for pos, point in enumerate(input):
    cluster = cls[pos]
    center = C[int(cluster)]  
    csse += np.sum((point-center)**2, axis=0)

  prev_centers = deepcopy(centers)

  cluster_p = []
  for k_i in range(0, k):
    cluster_p = []
    for pos, point in enumerate(input):
      if(int(cls[pos]) == k_i):
        cluster_p.append(point)
    centers[k_i] = np.mean(cluster_p, axis=0)

  E_O = deepcopy(diff)
  diff = np.sum((centers-prev_centers)**2, axis=1)

  # print(diff)

  psse = csse

  print("SSE:", psse)

  if np.sum(diff) == np.sum(E_O):
    break
  

Centers: [[5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [5.7 2.5 5.  2. ]]
SSE: 349.9909043401582
SSE: 124.42167928555489
SSE: 87.49345246688435
SSE: 79.96735746293821
SSE: 78.94084142614598
SSE: 78.94084142614598
SSE: 78.94084142614598


In [641]:
import statistics

org_cls = []
for i in range(0, k):
  c = []
  for idx, pnt in enumerate(data['type']):
    if i == pnt:
      c.append(idx)

  org_cls.append(c)

# print(org_cls)

pred_cls = []
for i in range(0, k):
  c = []
  for idx, pnt in enumerate(cls):
    if i == pnt:
      c.append(idx)

  pred_cls.append(c)

  pred_cls = sorted(pred_cls, key=lambda x : statistics.mean(x))
  
# print(pred_cls)

correct = 0
for idx, c in enumerate(org_cls):
  pred_c = pred_cls[idx]

  for point in c:
    if point in pred_c:
      correct += 1

acc = (correct*100)/150;

print("Accuracy: " + str(acc)+"%")

Accuracy: 89.33333333333333%


***K-means cosine:***

In [646]:
from statistics import mean
from copy import deepcopy
from scipy import spatial


k = 3
cols = ['slength', 'swidth', 'plength', 'pwidth']


input = data[cols].values

rand_idx = np.random.randint(len(input), size=k)
centers = input[rand_idx,:]
print("Centers:", centers)

prev_centers = np.zeros((3,4))
cls = np.array([0]*len(input))

diff = np.array(np.sum((centers-prev_centers)**2, axis=1))

psse = 0
csse = 0

for iteration in range(0, 100):
  
  for dd in diff:
    if dd != 0:
      continue

  for i in range(len(input)):
    d = []
    for x in range(0, k):
      d.append((1-spatial.distance.cosine(input[i], centers[x])))
    
    cl = d.index(min(d))
    cls[i] = cl

  # print(cls)

  csse = 0  
  for pos, point in enumerate(input):
    cluster = cls[pos]
    center = C[int(cluster)]  
    csse += np.sum((point-center)**2, axis=0)

  prev_centers = deepcopy(centers)

  cluster_p = []
  for k_i in range(0, k):
    cluster_p = []
    for pos, point in enumerate(input):
      if(int(cls[pos]) == k_i):
        cluster_p.append(point)
    centers[k_i] = np.mean(cluster_p, axis=0)

  # print(centers)

  E_O = deepcopy(diff)
  
  diff = []
  for x in range(0, k):
    ddd = 1-spatial.distance.cosine(centers[x], prev_centers[x])
    diff.append(np.nan_to_num(ddd))


  psse = csse

  print("SSE:", psse)

  if np.sum(diff) == np.sum(E_O):
    break


Centers: [[6.1 2.8 4.7 1.2]
 [5.5 2.6 4.4 1.2]
 [7.7 3.8 6.7 2.2]]
SSE: 1796.5282866014568
SSE: 213.21692646826202
SSE: 2294.827929240374
SSE: 201.67561331945873
SSE: 2294.827929240374


In [647]:
import statistics

org_cls = []
for i in range(0, k):
  c = []
  for idx, pnt in enumerate(data['type']):
    if i == pnt:
      c.append(idx)

  org_cls.append(c)

# print(org_cls)

pred_cls = []
for i in range(0, k):
  c = [150]
  for idx, pnt in enumerate(cls):
    if i == pnt:
      c.append(idx)

  pred_cls.append(c)

  pred_cls = sorted(pred_cls, key=lambda x : statistics.mean(x))
  
# print(pred_cls)

correct = 0
for idx, c in enumerate(org_cls):
  pred_c = pred_cls[idx]

  for point in c:
    if point in pred_c:
      correct += 1

acc = (correct*100)/150;

print("Accuracy: " + str(acc)+"%")

Accuracy: 66.66666666666667%


***Kmean with jaccard: ***

In [ ]:
from statistics import mean
from copy import deepcopy
from sklearn.metrics import jaccard_similarity_score

def jaccard(list1, list2):
  min_list = []
  max_list = []
  for i in range(0, len(list1)):
    min_list.append(min(list1[i], list2[i]))
    max_list.append(max(list1[i], list2[i]))
    
  return 1 - sum(min_list)/sum(max_list)

k = 3
cols = ['slength', 'swidth', 'plength', 'pwidth']


input = data[cols].values

rand_idx = np.random.randint(len(input), size=k)
centers = input[rand_idx,:]
print("Centers:", centers)

prev_centers = np.zeros((3,4))
cls = np.array([0]*len(input))

diff = np.array(np.sum((centers-prev_centers)**2, axis=1))

psse = 0
csse = 0

for iteration in range(0, 100):
  
  for d in diff:
    if d != 0:
      continue

  for i in range(len(input)):
    d = []
    for x in range(0, k):
      v = 1 - jaccard(list(input[i]), list(centers[x]))
      d.append(v)
    cl = np.argmin([d])
    cls[i] = cl

  csse = 0  
  for pos, point in enumerate(input):
    cluster = cls[pos]
    center = C[int(cluster)]  
    csse += np.sum((point-center)**2, axis=0)

  prev_centers = deepcopy(centers)

  cluster_p = []
  for k_i in range(0, k):
    cluster_p = []
    for pos, point in enumerate(input):
      if(int(cls[pos]) == k_i):
        cluster_p.append(point)
    centers[k_i] = np.mean(cluster_p, axis=0)

  E_O = deepcopy(diff)

  diff = []
  for x in range(0, k):
    ddd = 1-jaccard(list(centers[x]), list(prev_centers[x]))
    diff.append(np.nan_to_num(ddd))

  psse = csse

  print("SSE:", psse)

  if np.sum(diff) == np.sum(E_O):
    break

  

Centers: [[7.2 3.6 6.1 2.5]
 [5.8 4.  1.2 0.2]
 [6.7 2.5 5.8 1.8]]
SSE: 548.6765510859709
SSE: 1670.321481418306
SSE: 254.9431923767311
SSE: 2998.2702722659283
SSE: 279.19231135734043
SSE: 2990.3601662049864
SSE: 279.19231135734043


In [ ]:
import statistics

org_cls = []
for i in range(0, k):
  c = []
  for idx, pnt in enumerate(data['type']):
    if i == pnt:
      c.append(idx)

  org_cls.append(c)

# print(org_cls)

pred_cls = []
for i in range(0, k):
  c = [150]
  for idx, pnt in enumerate(cls):
    if i == pnt:
      c.append(idx)

  pred_cls.append(c)

  pred_cls = sorted(pred_cls, key=lambda x : statistics.mean(x))
  
# print(pred_cls)

correct = 0
for idx, c in enumerate(org_cls):
  pred_c = pred_cls[idx]

  for point in c:
    if point in pred_c:
      correct += 1

acc = (correct*100)/150;

print("Accuracy: " + str(acc)+"%")

Accuracy: 66.66666666666667%


**Q1:**

We can see that SSE of ecludian distance is smaller than Cosine-K-mean and Jaccard-K-means. Based on this data we an say that Euclidian is better than cosine and jaccard.

**Q2:**

Accuracy of Euclidian-K-mean is around over 88% while jaccard and cosine has a similarity of 66%. They are failing to differentiate between cluster two and cluster and three. Euclidian is better.

**Q3**

Euclidian requires more iteration compared to other two algorithms.

**Q4:**

Based on the above output, we can see that all the algorithms terminate before less than 100 iterations. However, euclidian-k-means algorithms save same value of SSE for last three iterations. But for Cosine and Jaccard, the SSE value oscilates before stabilizes.

If we execute the algorithm based on the change in SSE, ecludian algorithms terminates much quicker than Cosine and Jaccard k means algorithms. This reason behind this is that the SSE value keeps oscilating for the later two algorithms.

**Task 1**

In [604]:
def manhattan(t1, t2):
  return abs(t1[0] - t2[0]) + abs(t1[1] - t2[1])

def eucl(t1, t2):
  return (t1[0] - t2[0])**2 + (t1[1] - t2[1])**2

def print_centers(c):
  print("({:.2f}".format(c[0][0]), "{:.2f})".format(c[0][1]), "({:.2f}".format(c[1][0]), "{:.2f})".format(c[1][1]))


input = [(3,5), (3,4), (2,8), (2,3), (6,2), (6,4), (7,3), (7,4), (8,5), (7,6)]



print("========== Q1 ===========")

c1 = []
c2 = []

centers = [(4,6), (5,4)]

first_iter = True
while True:
  for point in input:
    if manhattan(point, centers[0]) > manhattan(point, centers[1]):
      c2.append(point)
    else:
      c1.append(point)

  center1 = (sum([t[0] for t in c1])/len(c1), sum([t[1] for t in c1])/len(c1))
  center2 = (sum([t[0] for t in c2])/len(c2), sum([t[1] for t in c2])/len(c2))

  new_centers = [center1, center2]

  if first_iter:
    print(c1, c2)
    first_iter = False
    print(new_centers)
    print_centers(new_centers)    




  if new_centers[0][0] == centers[0][0] and new_centers[0][1] == centers[0][1] and new_centers[1][0] == centers[1][0] and new_centers[1][1] == centers[1][1]:
    break
  else:
    c1 = []
    c2 = []
    centers = new_centers


print(c1, c2)
print_centers(centers)

print("========== Q2 ===========")

c1 = []
c2 = []

centers = [(4,6), (5,4)]

first_iter = True
while True:
  for point in input:
    if eucl(point, centers[0]) > eucl(point, centers[1]):
      c2.append(point)
    else:
      c1.append(point)

  center1 = (sum([t[0] for t in c1])/len(c1), sum([t[1] for t in c1])/len(c1))
  center2 = (sum([t[0] for t in c2])/len(c2), sum([t[1] for t in c2])/len(c2))

  new_centers = [center1, center2]
  if first_iter:
    print(c1, c2)
    first_iter = False
    print_centers(new_centers)    




  if new_centers[0][0] == centers[0][0] and new_centers[0][1] == centers[0][1] and new_centers[1][0] == centers[1][0] and new_centers[1][1] == centers[1][1]:
    break
  else:
    c1 = []
    c2 = []
    centers = new_centers


print(c1, c2)
print_centers(centers)


print("========== Q3 ===========")

c1 = []
c2 = []

centers = [(3,3), (8,3)]

first_iter = True
while True:
  for point in input:
    if manhattan(point, centers[0]) > manhattan(point, centers[1]):
      c2.append(point)
    else:
      c1.append(point)

  center1 = (sum([t[0] for t in c1])/len(c1), sum([t[1] for t in c1])/len(c1))
  center2 = (sum([t[0] for t in c2])/len(c2), sum([t[1] for t in c2])/len(c2))

  new_centers = [center1, center2]
  if first_iter:
    print(c1, c2)
    first_iter = False
    print_centers(new_centers)    




  if new_centers[0][0] == centers[0][0] and new_centers[0][1] == centers[0][1] and new_centers[1][0] == centers[1][0] and new_centers[1][1] == centers[1][1]:
    break
  else:
    c1 = []
    c2 = []
    centers = new_centers


print(c1, c2)
print_centers(centers)

print("========== Q4 ===========")

c1 = []
c2 = []

centers = [(3,2), (4,8)]

first_iter = True
while True:
  for point in input:
    if manhattan(point, centers[0]) > manhattan(point, centers[1]):
      c2.append(point)
    else:
      c1.append(point)

  center1 = (sum([t[0] for t in c1])/len(c1), sum([t[1] for t in c1])/len(c1))
  center2 = (sum([t[0] for t in c2])/len(c2), sum([t[1] for t in c2])/len(c2))

  new_centers = [center1, center2]
  if first_iter:
    print(c1, c2)
    first_iter = False
    print_centers(new_centers)    




  if new_centers[0][0] == centers[0][0] and new_centers[0][1] == centers[0][1] and new_centers[1][0] == centers[1][0] and new_centers[1][1] == centers[1][1]:
    break
  else:
    c1 = []
    c2 = []
    centers = new_centers


print(c1, c2)
print_centers(centers)


========== Q1 ===========
[(3, 5), (2, 8), (7, 6)] [(3, 4), (2, 3), (6, 2), (6, 4), (7, 3), (7, 4), (8, 5)]
[(4.0, 6.333333333333333), (5.571428571428571, 3.5714285714285716)]
(4.00 6.33) (5.57 3.57)
[(3, 5), (2, 8), (7, 6)] [(3, 4), (2, 3), (6, 2), (6, 4), (7, 3), (7, 4), (8, 5)]
(4.00 6.33) (5.57 3.57)
========== Q2 ===========
[(3, 5), (2, 8)] [(3, 4), (2, 3), (6, 2), (6, 4), (7, 3), (7, 4), (8, 5), (7, 6)]
(2.50 6.50) (5.75 3.88)
[(3, 5), (3, 4), (2, 8), (2, 3)] [(6, 2), (6, 4), (7, 3), (7, 4), (8, 5), (7, 6)]
(2.50 5.00) (6.83 4.00)
========== Q3 ===========
[(3, 5), (3, 4), (2, 8), (2, 3)] [(6, 2), (6, 4), (7, 3), (7, 4), (8, 5), (7, 6)]
(2.50 5.00) (6.83 4.00)
[(3, 5), (3, 4), (2, 8), (2, 3)] [(6, 2), (6, 4), (7, 3), (7, 4), (8, 5), (7, 6)]
(2.50 5.00) (6.83 4.00)
========== Q4 ===========
[(3, 5), (3, 4), (2, 3), (6, 2), (6, 4), (7, 3), (7, 4)] [(2, 8), (8, 5), (7, 6)]
(4.86 3.57) (5.67 6.33)
[(3, 5), (3, 4), (2, 3), (6, 2), (6, 4), (7, 3), (7, 4)] [(2, 8), (8, 5), (7, 6)]
(4.8

**Task 4:**

In [649]:
import math

c1 = [(4.7, 3.2), (4.9, 3.1), (5.0, 3.0), (4.6, 2.9)]
c2 = [(5.9, 3.2), (6.7, 3.1), (6.0, 3.0), (6.2, 2.8)]

def eucl(t1, t2):
  return math.sqrt((t1[0] - t2[0])**2 + (t1[1] - t2[1])**2)

max_distance = 0
min_distance = 1000000

total_distance = 0
total_distance1 = 0
total_distance2 = 0

for p1 in c1:
  for p2 in c2:
    d = eucl(p1, p2)
    if d > max_distance:
      max_distance = d

print(max_distance)

for p1 in c1:
  for p2 in c2:
    d = eucl(p1, p2)
    if d < min_distance:
      min_distance = d

print(min_distance)

for p1 in c1:
  for p2 in c2:
    d = eucl(p1, p2)
    total_distance += d


print(total_distance/16)


2.109502310972899
0.9219544457292891
1.4128564854895742
